### ISSUE TITLE
Project Manager

### ISSUE THREAD

**Issue by stdlibdoh** [stdlibdoh/swproj-l#2]
So, after speaking with a few other groups, I think we have to pick a Project Manager for our group. I suggest we wait for our meeting with the supervisor, just to see if we get the whole group together, as opposed to just us 3. We can then have a discussion on it. If the supervisor complains about it, we'll just explain that such a decision shouldn't be made by half the group.

Anyway, just thought I'd flag that up so we're not caught off guard during the meeting. If you have different thoughts though, share them with the group.

**Comment by nedelculiviu95** [comment]
I remember that Nick told us the same thing, to chose a Project Manager from the first course. I wanted to bring it up but I forget to do it. You will be the Project Manager so don't worry about it :)). You have more knowledge that the rest of us, not only in technology but in life as well, so you have my vote.

**Comment by rajuabedin** [comment]
+1 From me too
